### ISSUE TITLE
Хочу пообщаться по поводу трудоустройства

### ISSUE THREAD

**Issue by OlegGilyazov** [nsdwtfcode/testpage1#1]
Добрый день! Заинтересовало ваше резюме (https://ufa.hh.ru/resume/4d3f2365000713ec050039ed1f576d7146794e), оно же ваше? Хотел бы пообщаться, если поиск работы для вас актуален. Другими способами связаться не получилось.

Мой email - oleggilyazov@yandex.ru.

**Comment by nsdwtfcode** [comment]
Ой)) Да можно, на всякий телеграмм @NSDcode

пт, 18 нояб. 2022 г. в 12:41, OlegGilyazov ***@***.***>:

**Comment by OlegGilyazov** [comment]
Closed
